// Generated by build_features.py, do not edit by hand.
var SALT_DATA = {
 "salts": [
  {
   "key": "CF",
   "no": 1,
   "name": "Calc Fluor",
   "latin": "Calcarea fluorica"
  },
  {
   "key": "CP",
   "no": 2,
   "name": "Calc Phos",
   "latin": "Calcarea phosphorica"
  },
  {
   "key": "FP",
   "no": 3,
   "name": "Ferrum Phos",
   "latin": "Ferrum phosphoricum"
  },
  {
   "key": "KM",
   "no": 4,
   "name": "Kali Mur",
   "latin": "Kali muriaticum (Kalium chloratum)"
  },
  {
   "key": "KP",
   "no": 5,
   "name": "Kali Phos",
   "latin": "Kali phosphoricum"
  },
  {
   "key": "KS",
   "no": 6,
   "name": "Kali Sulph",
   "latin": "Kali sulphuricum"
  },
  {
   "key": "MP",
   "no": 7,
   "name": "Mag Phos",
   "latin": "Magnesia phosphorica"
  },
  {
   "key": "NM",
   "no": 8,
   "name": "Nat Mur",
   "latin": "Natrum muriaticum"
  },
  {
   "key": "NP",
   "no": 9,
   "name": "Nat Phos",
   "latin": "Natrum phosphoricum"
  },
  {
   "key": "NS",
   "no": 10,
   "name": "Nat Sulph",
   "latin": "Natrum sulphuricum"
  },
  {
   "key": "SI",
   "no": 11,
   "name": "Silicea",
   "latin": "Silicea"
  },
  {
   "key": "CS",
   "no": 12,
   "name": "Calc Sulph",
   "latin": "Calcarea sulphurica"
  }
 ],
 "areas": [
  "Inflammation & pus",
  "Discharge & mucus",
  "Fever",
  "Pain",
  "Digestion & appetite",
  "Stool & bowels",
  "Mouth, tongue & teeth",
  "Skin",
  "Bones, joints & muscles",
  "Veins & glands",
  "Bleeding",
  "Nerves & sleep",
  "Mind & mood",
  "General picture",
  "Children",
  "Worse from",
  "Better from",
  "Time & side"
 ],
 "features": [
  {
   "group": "Tissue affinity",
   "feature": "Bone surface, tooth enamel, elastic fibres",
   "salts": {
    "CF": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Bones, teeth, growth, new cell formation",
   "salts": {
    "CP": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Blood (oxygen carrier), muscle walls of vessels",
   "salts": {
    "FP": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Fibrin; mucous membranes; glands",
   "salts": {
    "KM": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Brain and nerves (nutrition of nerve tissue)",
   "salts": {
    "KP": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Skin surface (epidermis) and linings (epithelium)",
   "salts": {
    "KS": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Nerves and muscles (contraction / spasm)",
   "salts": {
    "MP": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Water distribution in tissues; mucus",
   "salts": {
    "NM": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Acid balance (lactic & uric acid); fat digestion",
   "salts": {
    "NP": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Removal of excess water; liver, bile, kidneys",
   "salts": {
    "NS": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Connective tissue, skin, hair, nails",
   "salts": {
    "SI": "AB"
   },
   "areas": []
  },
  {
   "group": "Tissue affinity",
   "feature": "Suppuration / healing of discharging wounds",
   "salts": {
    "CS": "B",
    "SI": "AB"
   },
   "areas": []
  },
  {
   "group": "Inflammation stage",
   "feature": "1st stage: redness, heat, throbbing, fever onset, no discharge yet",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Inflammation & pus",
    "Fever"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "2nd stage: swelling, white/grey fibrinous exudation",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Inflammation & pus"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "3rd stage: yellow discharge, peeling / desquamation",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Inflammation & pus"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "Inflamed skin/tissue before pus forms (phlegmonous)",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Inflammation & pus"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "Pus forming; abscess needs to ripen / come to a head",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Inflammation & pus",
    "Skin"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "Pus with an outlet; discharge goes on too long, slow to heal",
   "salts": {
    "CS": "B"
   },
   "areas": [
    "Inflammation & pus",
    "Skin"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "Discharge turns foul / septic / gangrenous",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Inflammation & pus",
    "Discharge & mucus"
   ]
  },
  {
   "group": "Inflammation stage",
   "feature": "Hard lump (induration) left behind",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Inflammation & pus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Clear, watery, transparent, frothy (like raw egg-white / boiled starch)",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Albuminous, like white of egg (not watery)",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Thick, white, fibrinous, milky",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Yellow, slimy (sometimes watery)",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Golden-yellow, creamy, honey-coloured",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Green / yellowish-green",
   "salts": {
    "NS": "AB",
    "KS": "B",
    "SI": "B"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Thick yellow pus",
   "salts": {
    "SI": "AB",
    "NP": "A",
    "CS": "B"
   },
   "areas": [
    "Discharge & mucus",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Thick, yellow, lumpy (Calc Sulph: may be blood-tinged)",
   "salts": {
    "CS": "B",
    "CF": "B"
   },
   "areas": [
    "Discharge & mucus",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Foul, fetid, carrion-like smell",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Discharge & mucus",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Acrid / excoriating (burns the skin)",
   "salts": {
    "NM": "AB",
    "KP": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "Watery exudation that is yellowish",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Discharge",
   "feature": "No discharge at all (dry, red, hot)",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Discharge & mucus"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Clean and red / dark-red swollen",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "White or greyish-white coating (not slimy)",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Clean & moist, or frothy bubbles of saliva along the edges",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Yellow, slimy coating",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Moist, creamy, golden-yellow coating at the back",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Dirty brownish-green / greyish-green, bitter taste",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Brownish, like liquid mustard; dry; offensive breath",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Clean tongue with stomach cramps",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Clay-coloured, yellow at base, flabby",
   "salts": {
    "CS": "B"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Cracked, hardened",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "White-furred, swollen, numb or stiff",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Hardened / ulcer / feels like a hair on it",
   "salts": {
    "SI": "B"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Tongue",
   "feature": "Mapped tongue",
   "salts": {
    "NM": "B",
    "KM": "B"
   },
   "areas": [
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Throbbing / stitching with heat & redness",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Pain"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Shooting, lightning-like, boring, cramping, constricting; changes place",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Pain",
    "Nerves & sleep"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Pain with a paralysed / lame feeling; followed by exhaustion",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Pain"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Pain with numbness, coldness or crawling (ants) sensation",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "Pain",
    "Nerves & sleep"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Shifting, wandering pains",
   "salts": {
    "KS": "B",
    "MP": "AB"
   },
   "areas": [
    "Pain"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Pain with tears, salivation or vomiting of water",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Pain"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Pain with vomiting of bile",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Pain",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Deep pain as if ulcerating; small nodules on scalp",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Pain"
   ]
  },
  {
   "group": "Pain type",
   "feature": "Dragging, bearing-down pain (relaxed tissues)",
   "salts": {
    "CF": "B"
   },
   "areas": [
    "Pain",
    "Veins & glands"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Motion",
   "salts": {
    "FP": "AB",
    "KM": "AB",
    "CP": "B"
   },
   "areas": [
    "Worse from",
    "Pain"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Light touch",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Cold, cold air, draughts, cold washing",
   "salts": {
    "MP": "B",
    "SI": "B",
    "CP": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Warm / heated room",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Rest, rising from sitting, beginning to move, exertion",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Worse from",
    "Pain"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Noise",
   "salts": {
    "KP": "B",
    "SI": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Being alone",
   "salts": {
    "KP": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Damp, wet weather; living near water / damp houses",
   "salts": {
    "NS": "AB",
    "CF": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Getting wet; change of weather",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Working / washing in water",
   "salts": {
    "CS": "B",
    "NS": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Sea-side; cold weather",
   "salts": {
    "NM": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Thunderstorm",
   "salts": {
    "NP": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Fatty or rich food, pastry",
   "salts": {
    "KM": "B",
    "NP": "AB"
   },
   "areas": [
    "Worse from",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Chilled feet / suppressed foot-sweat",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Lying on left side",
   "salts": {
    "NS": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Worse from",
   "feature": "Consolation",
   "salts": {
    "NM": "B"
   },
   "areas": [
    "Worse from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Cold applications / cold drinks",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Warmth, heat, hot drinks",
   "salts": {
    "MP": "AB",
    "SI": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Pressure, bending double, rubbing",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Better from",
    "Pain"
   ]
  },
  {
   "group": "Better from",
   "feature": "Cool, open air",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Gentle motion; eating; company; pleasant excitement",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Lying down",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Lying on something hard (backache)",
   "salts": {
    "NM": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Warm, dry weather",
   "salts": {
    "NS": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Wrapping up warmly (esp. the head)",
   "salts": {
    "SI": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Better from",
   "feature": "Sleep",
   "salts": {
    "FP": "B"
   },
   "areas": [
    "Better from"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Worse in the evening",
   "salts": {
    "KS": "AB",
    "NP": "B"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Worse in the morning",
   "salts": {
    "NM": "B"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Worse at night",
   "salts": {
    "SI": "B",
    "CP": "AB"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Comes at set times / periodical",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Right-sided complaints",
   "salts": {
    "MP": "B"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Time & side",
   "feature": "Worse at full moon",
   "salts": {
    "SI": "B"
   },
   "areas": [
    "Time & side"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Nervous exhaustion, brain-fag, poor memory",
   "salts": {
    "KP": "AB",
    "SI": "B",
    "NM": "B"
   },
   "areas": [
    "Mind & mood",
    "Nerves & sleep"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Anxious, fearful, weepy, homesick, suspicious, shy",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Depressed; groundless fear of money troubles; indecisive",
   "salts": {
    "CF": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Peevish, fretful (children); after grief or disappointment",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Mind & mood",
    "Children"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Trifles seem like mountains; indifferent",
   "salts": {
    "FP": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Imagines he must starve",
   "salts": {
    "KM": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Fear of falling; sad, anxious",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Forgetful, dull; complains constantly about the pain",
   "salts": {
    "MP": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Hopeless, sad, weepy; worse from consolation",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Apprehensive; irritable over trifles",
   "salts": {
    "NP": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Low, irritable from 'biliousness'; worse from sad music",
   "salts": {
    "NS": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Can't concentrate, tires easily, oversensitive",
   "salts": {
    "SI": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "Mind & mood",
   "feature": "Changeable mood",
   "salts": {
    "CS": "B",
    "KP": "B"
   },
   "areas": [
    "Mind & mood"
   ]
  },
  {
   "group": "General picture",
   "feature": "Watery, puffy face; tired, sleepy, chilly; craves salt",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "General picture",
    "Digestion & appetite"
   ]
  },
  {
   "group": "General picture",
   "feature": "Pale, sensitive, irritable, easily exhausted",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "General picture",
    "Mind & mood"
   ]
  },
  {
   "group": "General picture",
   "feature": "Thin, anaemic, slow growth; craves salty/smoked meats",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "General picture",
    "Digestion & appetite",
    "Children"
   ]
  },
  {
   "group": "General picture",
   "feature": "Flushed, florid face",
   "salts": {
    "FP": "B"
   },
   "areas": [
    "General picture"
   ]
  },
  {
   "group": "General picture",
   "feature": "Lean, nervous, tired, can't sit up; craves sugar",
   "salts": {
    "MP": "B"
   },
   "areas": [
    "General picture",
    "Digestion & appetite"
   ]
  },
  {
   "group": "General picture",
   "feature": "Feels the damp; sallow / jaundiced; bilious",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "General picture"
   ]
  },
  {
   "group": "General picture",
   "feature": "Chilly, poorly nourished, sweaty head, offensive foot-sweat",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "General picture"
   ]
  },
  {
   "group": "General picture",
   "feature": "Relaxed, sagging tissues",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "General picture",
    "Veins & glands"
   ]
  },
  {
   "group": "General picture",
   "feature": "Sour smell / sour symptoms everywhere",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "General picture",
    "Digestion & appetite"
   ]
  },
  {
   "group": "General picture",
   "feature": "Thirst for cold water",
   "salts": {
    "FP": "B"
   },
   "areas": [
    "General picture",
    "Digestion & appetite"
   ]
  },
  {
   "group": "General picture",
   "feature": "Craves fruit, sour green vegetables",
   "salts": {
    "CS": "B"
   },
   "areas": [
    "General picture",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Vomits undigested food",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Vomits bile; bitter taste",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Vomits clear water or stringy mucus; water-brash",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Retches up white mucus",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Sour burps, heartburn, sour or curdled vomit",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Cramping colic, better with heat & bending double; burping no relief",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Digestion & appetite",
    "Stool & bowels",
    "Pain"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Pressure / fullness in stomach with yellow tongue",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Digestion & appetite"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Flatulent colic with constipation",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Digestion & appetite",
    "Stool & bowels",
    "Pain"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Nervous 'gone' feeling; stomach ache from fright",
   "salts": {
    "KP": "B"
   },
   "areas": [
    "Digestion & appetite",
    "Mind & mood"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Stomach pain eased by eating / colic each time child feeds",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Digestion & appetite",
    "Pain",
    "Children"
   ]
  },
  {
   "group": "Digestion",
   "feature": "Indigestion after fatty food",
   "salts": {
    "KM": "B",
    "NP": "AB"
   },
   "areas": [
    "Digestion & appetite",
    "Worse from"
   ]
  },
  {
   "group": "Stool",
   "feature": "Watery, mucous diarrhoea",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Carrion-smelling, putrid",
   "salts": {
    "KP": "AB",
    "SI": "B"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Watery-bilious, green",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Bloody-mucous; or pale, clay-coloured",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Sour-smelling, green",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite",
    "Children"
   ]
  },
  {
   "group": "Stool",
   "feature": "Undigested",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Watery, with cramping colic before each stool",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite",
    "Pain"
   ]
  },
  {
   "group": "Stool",
   "feature": "Purulent",
   "salts": {
    "NP": "A",
    "SI": "A",
    "CS": "B"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Stool",
   "feature": "Dry, hard, crumbling constipation",
   "salts": {
    "NM": "B"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Stool slips back after partly expelled",
   "salts": {
    "SI": "B"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite"
   ]
  },
  {
   "group": "Stool",
   "feature": "Green, slimy, hot, sputtering; worse fruit",
   "salts": {
    "CP": "B"
   },
   "areas": [
    "Stool & bowels",
    "Digestion & appetite",
    "Children"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Clear, watery contents",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Thick white (fibrinous) contents",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Albuminous contents",
   "salts": {
    "CP": "A"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Honey-yellow contents",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Yellowish-watery contents",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Pus-like contents",
   "salts": {
    "NP": "A",
    "SI": "A"
   },
   "areas": [
    "Skin",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Skin: blisters",
   "feature": "Bloody, foul contents",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Mealy, flour-like scurf",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Yellowish-white crusts",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "White scales",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Honey-yellow crusts",
   "salts": {
    "NP": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Yellowish scales",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Yellow, purulent crusts",
   "salts": {
    "SI": "A",
    "CS": "B"
   },
   "areas": [
    "Skin",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Greasy, foul-smelling crusts",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Profuse peeling on a sticky base",
   "salts": {
    "KS": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: crusts",
   "feature": "Hard skin on palms with cracks",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Cracks, chaps, fissures",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Itching",
   "salts": {
    "MP": "A",
    "CP": "B",
    "KP": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Hives / nettle-rash",
   "salts": {
    "KP": "A",
    "NM": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Boils, abscesses",
   "salts": {
    "SI": "AB",
    "CS": "B"
   },
   "areas": [
    "Skin",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Brittle nails, white spots, ingrowing nails",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Warts",
   "salts": {
    "KM": "AB",
    "NS": "AB",
    "NM": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Burns that blister",
   "salts": {
    "NM": "A",
    "KM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Insect stings",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Chilblains",
   "salts": {
    "NS": "A",
    "KM": "B",
    "KP": "B",
    "SI": "B",
    "CS": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Hair loss / bald patches",
   "salts": {
    "KP": "AB",
    "NM": "AB",
    "KS": "B",
    "SI": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Skin: other",
   "feature": "Dandruff",
   "salts": {
    "KM": "B",
    "KS": "B",
    "NM": "B",
    "MP": "B"
   },
   "areas": [
    "Skin"
   ]
  },
  {
   "group": "Bleeding",
   "feature": "Bright red, clots easily",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Bleeding"
   ]
  },
  {
   "group": "Bleeding",
   "feature": "Dark, thick, sticky, clotted",
   "salts": {
    "KM": "AB"
   },
   "areas": [
    "Bleeding"
   ]
  },
  {
   "group": "Bleeding",
   "feature": "Thin, watery, does not clot",
   "salts": {
    "KP": "AB",
    "NM": "AB"
   },
   "areas": [
    "Bleeding"
   ]
  },
  {
   "group": "Bleeding",
   "feature": "Nosebleeds in children",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Bleeding",
    "Children"
   ]
  },
  {
   "group": "Fever",
   "feature": "Start of any fever; chilly stage; quick pulse",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Fever",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Fever",
   "feature": "Exhausted, stuporous fever; dry brown tongue",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Fever"
   ]
  },
  {
   "group": "Fever",
   "feature": "Drowsy fever with watery vomiting",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Fever"
   ]
  },
  {
   "group": "Fever",
   "feature": "Recurring (intermittent) fever",
   "salts": {
    "NS": "AB",
    "NM": "AB"
   },
   "areas": [
    "Fever"
   ]
  },
  {
   "group": "Fever",
   "feature": "Temperature rises in the evening; helps sweating",
   "salts": {
    "KS": "B"
   },
   "areas": [
    "Fever"
   ]
  },
  {
   "group": "Fever",
   "feature": "Fever while pus is forming (hectic)",
   "salts": {
    "CS": "B",
    "SI": "B"
   },
   "areas": [
    "Fever",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Fever",
   "feature": "Influenza",
   "salts": {
    "NS": "AB"
   },
   "areas": [
    "Fever",
    "Discharge & mucus"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Cramps, spasms, hiccough, writer's cramp",
   "salts": {
    "MP": "AB"
   },
   "areas": [
    "Nerves & sleep",
    "Pain",
    "Bones, joints & muscles"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Convulsions with fever (teething)",
   "salts": {
    "FP": "AB"
   },
   "areas": [
    "Nerves & sleep",
    "Children",
    "Fever"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Spasms in anaemic, weak children",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "Nerves & sleep",
    "Children"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Weakness, paralysis, nervous collapse",
   "salts": {
    "KP": "AB"
   },
   "areas": [
    "Nerves & sleep"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Numbness, pins & needles",
   "salts": {
    "CP": "AB",
    "NM": "B"
   },
   "areas": [
    "Nerves & sleep",
    "Pain"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Sleepless from worry or excitement",
   "salts": {
    "KP": "B"
   },
   "areas": [
    "Nerves & sleep",
    "Mind & mood"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Sleepy, unrefreshed on waking",
   "salts": {
    "NM": "AB"
   },
   "areas": [
    "Nerves & sleep"
   ]
  },
  {
   "group": "Nerves & sleep",
   "feature": "Attacks at night",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Nerves & sleep"
   ]
  },
  {
   "group": "Structure",
   "feature": "Slow bone growth, fractures slow to knit, late teeth, open fontanelles",
   "salts": {
    "CP": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Children",
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Structure",
   "feature": "Hard knobby bone growths; stony-hard lumps",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Bones, joints & muscles"
   ]
  },
  {
   "group": "Structure",
   "feature": "Loose teeth, rough enamel",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Mouth, tongue & teeth"
   ]
  },
  {
   "group": "Structure",
   "feature": "Varicose veins, piles, sagging / prolapse",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Veins & glands",
    "Stool & bowels"
   ]
  },
  {
   "group": "Structure",
   "feature": "Bone inflammation tending to pus",
   "salts": {
    "SI": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Inflammation & pus"
   ]
  },
  {
   "group": "Structure",
   "feature": "Glands swollen, soft",
   "salts": {
    "KM": "B",
    "NP": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Veins & glands"
   ]
  },
  {
   "group": "Structure",
   "feature": "Glands swollen, stony hard",
   "salts": {
    "CF": "AB"
   },
   "areas": [
    "Bones, joints & muscles",
    "Veins & glands"
   ]
  },
  {
   "group": "Structure",
   "feature": "Glands suppurating",
   "salts": {
    "SI": "AB",
    "CS": "B"
   },
   "areas": [
    "Bones, joints & muscles",
    "Inflammation & pus",
    "Veins & glands"
   ]
  },
  {
   "group": "Structure",
   "feature": "Joint / gout pains from uric acid",
   "salts": {
    "NP": "AB",
    "SI": "AB",
    "NS": "B"
   },
   "areas": [
    "Bones, joints & muscles",
    "Pain"
   ]
  },
  {
   "group": "Structure",
   "feature": "Fluid in joints / sacs (e.g. knee)",
   "salts": {
    "CP": "AB",
    "SI": "AB",
    "NM": "A"
   },
   "areas": [
    "Bones, joints & muscles"
   ]
  }
 ]
};
if (typeof module !== 'undefined') module.exports = SALT_DATA;
